### PR TITLE
Adds input permutations to TYPES tests.

### PR DESCRIPTION
**Pull request by osadi**
I started poking around and ran in to some issues where my assumptions failed me. I'm not sure if this is what MikroValid is supposed to handle, or if I'm doing it wrong.

Added are a couple of permutations to the input in the TYPES category, and with this I have 37 failing cases. Also note that I'm new to AVA so I might be way off on everything here and there's a mixed bag of false positives/negatives in there as well.

Here's to hoping that a draft PR is the way to go to illustrate my thoughts/issues.

### CODE REVIEW

**Comment by mikaelvesavuori** [comment]
Hi @osadi! Let me get this right: Your idea is to simplify the test case count by programmatically generating them?

Also, if you have specific examples of things you've tried (but failed using), I'll be happy to look at them irrespective of the PR.

**Comment by mikaelvesavuori** [comment]
Also: This is really comprehensive - I'll see what I can find. It seems like most of the errors are from the negative test cases.

**Comment by osadi** [comment]
Well, not exactly. I was passing an object to the type string. Like
```

test('It should invalidate a string that does not have the correct type', (t) => {
  const expected = false;
  const { success } = match.test(
    {
      properties: {
        username: {
          type: 'string'
        }
      }
    },
    {
      username: {}
    }
  );

  t.is(success, expected);
});
```
And it validated. Or rather, did not invalidate.

So I tried throwing as much as possible at it to see what was actually invalid. And ended up with this. And as you say, It's mostly the invalidations that fail. 

And when I say fail, I mean my assumptions. It might not be what you're aiming for 😄

**Comment by mikaelvesavuori** [comment]
Yeah, so it doesn't validate root keys if they aren't mapped to something in the schema. That's why you get the effect you get.

EDIT: Still looking. I might be mumbling.

**Comment by mikaelvesavuori** [comment]
Thanks @osadi! This is now merged and I got it working after revising some of how the validation logic works.

With that said, this will _not_ work for the cases you provided with Symbols in objects. I removed the test cases and the validation implementation (as of now) does not allow Symbols there.

**Comment by osadi** [comment]
Happy to help 👍 and glad I didn't send you on a wild goose chase.
Checking for `object` in JS is.. not straight forward.

**Pull request merged**
